run:
  timeout: 5m
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  gci:
    local-prefixes: jsonpathplus-go
  
  gocognit:
    min-complexity: 15
  
  gocyclo:
    min-complexity: 15
  
  godot:
    scope: declarations
    capital: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: jsonpathplus-go
  
  golint:
    min-confidence: 0
  
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  
  govet:
    check-shadowing: true
  
  lll:
    line-length: 120
  
  maligned:
    suggest-new: true
  
  misspell:
    locale: US
  
  nestif:
    min-complexity: 4
  
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  
  revive:
    min-confidence: 0
  
  unparam:
    check-exported: false
  
  unused:
    check-exported: false
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
    
    - path: examples/
      linters:
        - gomnd
        - funlen
    
    - linters:
        - lll
      source: "^//go:generate "
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false