run:
  timeout: 5m

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/reclaimprotocol/jsonpathplus-go)
  
  gocognit:
    min-complexity: 15
  
  gocyclo:
    min-complexity: 15
  
  godot:
    scope: declarations
    capital: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/reclaimprotocol/jsonpathplus-go
  
  mnd:
    ignored-numbers: [0, 1, 2]
    ignored-functions: 
      - 'strconv.FormatInt'
      - 'strconv.FormatUint'
      - 'strconv.ParseInt'
  
  govet:
    enable-all: true
    settings:
      shadow:
        strict: true
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
  
  nestif:
    min-complexity: 4
  
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  
  revive:
    confidence: 0
  
  unparam:
    check-exported: false
  
  unused:
    field-writes-are-uses: true
    post-statements-are-reads: false
    exported-is-used: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocognit
        - gocyclo
    
    - path: cmd/examples/
      linters:
        - mnd
        - funlen
    
    - linters:
        - lll
      source: "^//go:generate "
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0