run:
  timeout: 5m

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/reclaimprotocol/jsonpathplus-go
  
  govet:
    enable-all: false
    enable:
      - atomic
      - bools
      - buildtag
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
    # Disable noisy checks
    disable:
      - shadow        # Too many false positives
      - fieldalignment # Not worth the effort
  
  misspell:
    locale: US

linters:
  enable:
    # Critical - these find real bugs
    - errcheck      # Check error returns
    - gosec         # Security issues
    - staticcheck   # Serious bugs
    - govet         # Suspicious constructs
    - typecheck     # Type errors
    - ineffassign   # Ineffective assignments
    - unused        # Unused code
    
    # Important formatting
    - gofmt         # Standard formatting
    - goimports     # Import organization
    
    # Useful but not critical
    - gosimple      # Simplification suggestions
    - unconvert     # Unnecessary conversions
    - misspell      # Spelling errors
    
    # Disabled - too noisy or not valuable
    # - asciicheck    # ASCII identifiers only
    # - bodyclose     # HTTP response body closing
    # - dogsled       # Blank identifiers
    # - dupl          # Code duplication
    # - exhaustive    # Exhaustive switches
    # - funlen        # Function length
    # - gci           # Import grouping
    # - gochecknoinits # No init functions
    # - gocognit      # Cognitive complexity
    # - goconst       # Extract constants
    # - gocritic      # Various opinionated checks
    # - gocyclo       # Cyclomatic complexity
    # - godot         # Comment punctuation
    # - mnd           # Magic numbers
    # - goprintffuncname # Printf-like function names
    # - lll           # Line length
    # - nakedret      # Naked returns
    # - nestif        # Nested if statements
    # - noctx         # Context in HTTP requests
    # - nolintlint    # Nolint directives
    # - prealloc      # Preallocate slices
    # - revive        # Various style rules
    # - stylecheck    # Style rules
    # - unparam       # Unused parameters
    # - whitespace    # Unnecessary whitespace

issues:
  exclude-rules:
    # Tests can be more relaxed
    - path: _test\.go
      linters:
        - errcheck  # Test helper functions often ignore errors
    
    # Examples are meant to be simple and clear
    - path: cmd/examples/
      linters:
        - errcheck  # Examples often skip error handling for clarity
  
  exclude-use-default: true  # Use default exclusions
  max-issues-per-linter: 50
  max-same-issues: 10