project_name: jsonpathplus-go

# Build configuration
builds:
  - id: jsonpath-example
    dir: cmd/examples/production
    main: ./production.go
    binary: jsonpath-example
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.BuildTime={{.Date}}

# Archive configuration
archives:
  - id: default
    builds:
      - jsonpath-example
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - "docs/**"
      - "cmd/examples/**"

# Checksum configuration
checksum:
  name_template: "checksums.txt"

# Snapshot configuration
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

# Release configuration
release:
  github:
    owner: reclaimprotocol
    name: jsonpathplus-go
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## JSONPath Plus Go v{{.Version}}
    
    🎉 **100% JavaScript Compatibility Maintained**
    
    This release brings complete string index tracking functionality while maintaining perfect compatibility with JavaScript JSONPath-Plus.
    
    ### ✨ Highlights
    - **String Index Tracking**: Complete character position tracking in JSON strings
    - **100% Compatibility**: All 50 JavaScript compatibility tests passing
    - **Production Ready**: All CI/CD checks passing with comprehensive test coverage
    
    ### What's Changed
  footer: |
    **Full Changelog**: https://github.com/reclaimprotocol/jsonpathplus-go/compare/{{.PreviousTag}}...{{.Tag}}

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "Other Changes"
      order: 999

# Docker images - disabled (no Docker setup for this project)
# dockers: []

# Source archives
source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Version }}-source"
  format: tar.gz

# Git configuration
git:
  ignore_tags:
    - "{{ .Env.IGNORE_TAG }}"

# Before hooks
before:
  hooks:
    - go mod tidy
    - go mod verify
    - go test -short ./...

# Publishers and SBOMs disabled for this project
# publishers: []
# sboms: []