const { JSONPath } = require('jsonpath-plus');
const data = {users: {'1': {name: 'Alice'}, '2': {name: 'Bob'}}};

// Get the actual paths generated by JavaScript
console.log('JavaScript path formats:');
const results = JSONPath({ path: '$.users[*]', json: data, resultType: 'all' });
results.forEach(r => {
    console.log('Value:', JSON.stringify(r.value), 'Path:', r.path);
});

// Test what paths should match
console.log('\nTesting path filters:');
console.log('1. $.users[?(@path === "$[\'users\'][\'1\']")]');
let res1 = JSONPath({ path: '$.users[?(@path === "$[\'users\'][\'1\']")]', json: data });
console.log('Count:', res1.length);

console.log('2. $.users[?(@path === "$[\'users\'][1]")]');
let res2 = JSONPath({ path: '$.users[?(@path === "$[\'users\'][1]")]', json: data });
console.log('Count:', res2.length);

console.log('3. $.users[?(@path)]');
let res3 = JSONPath({ path: '$.users[?(@path)]', json: data });
console.log('Count:', res3.length);

// Test string vs number indexing
console.log('\nTesting different data types:');
const data2 = {arr: ['a', 'b', 'c']};
const arrResults = JSONPath({ path: '$.arr[*]', json: data2, resultType: 'all' });
arrResults.forEach(r => {
    console.log('Array Value:', JSON.stringify(r.value), 'Path:', r.path);
});